# Generated by Django 3.0 on 2019-12-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kdcuser',
            name='uid',
        ),
        migrations.AddField(
            model_name='kdcuser',
            name='id',
            field=models.AutoField(auto_created=True, default=222, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
