# Generated by Django 3.0 on 2019-12-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KDC', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
