# Generated by Django 3.0 on 2019-12-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDC', '0002_auto_20191214_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
