# Generated by Django 3.0 on 2019-12-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDC', '0004_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='applications',
            field=models.ManyToManyField(to='KDC.Application'),
        ),
    ]
