# Generated by Django 3.0 on 2019-12-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGS', '0001_initial'),
        ('KDC', '0006_application_date_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.AlterField(
            model_name='user',
            name='applications',
            field=models.ManyToManyField(to='TGS.Application'),
        ),
    ]
