# Generated by Django 3.0 on 2019-12-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Application Name')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Application Key')),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
