# Generated by Django 3.0 on 2019-12-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='key',
            field=models.CharField(max_length=8, unique=True, verbose_name='Application Key'),
        ),
    ]
